import type { Customer, Product, Quotation } from "@/src/types/index"

export const DUMMY_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    title: "Modern Sofa",
    category: "Sofa",
    price: 45000,
    images: ["/modern-sofa.png"],
    stock: 5,
    description: "Comfortable 3-seater modern sofa",
  },
  {
    id: "prod-2",
    title: "Wooden Dining Table",
    category: "Table",
    price: 28000,
    images: ["/wooden-dining-table.png"],
    stock: 8,
    description: "Solid teak wood dining table",
  },
  {
    id: "prod-3",
    title: "Office Chair",
    category: "Chair",
    price: 12000,
    images: ["/ergonomic-office-chair.png"],
    stock: 15,
    description: "Ergonomic office chair with lumbar support",
  },
  {
    id: "prod-4",
    title: "King Bed Frame",
    category: "Bed",
    price: 55000,
    images: ["/king-bed-frame.jpg"],
    stock: 3,
    description: "Premium king-size bed frame",
  },
  {
    id: "prod-5",
    title: "Coffee Table",
    category: "Table",
    price: 8500,
    images: ["/modern-living-room-coffee-table.png"],
    stock: 12,
    description: "Glass and wood coffee table",
  },
]

export const DUMMY_CUSTOMERS: Customer[] = [
  {
    id: "cust-1",
    name: "Rajesh Kumar",
    phone: "+919876543210",
    whatsapp: "+919876543210",
    email: "rajesh@example.com",
    tags: ["repeat", "high-value"],
    assignedEmployeeId: "emp-1",
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    lastContact: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "cust-2",
    name: "Priya Singh",
    phone: "+919876543211",
    whatsapp: "+919876543211",
    email: "priya@example.com",
    tags: ["new"],
    assignedEmployeeId: "emp-1",
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "cust-3",
    name: "Amit Patel",
    phone: "+919876543212",
    whatsapp: "+919876543212",
    email: "amit@example.com",
    tags: ["converted"],
    assignedEmployeeId: "emp-1",
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    lastContact: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

export const DUMMY_QUOTATIONS: Quotation[] = [
  {
    id: "quot-1",
    customerId: "cust-1",
    employeeId: "emp-1",
    items: [
      { productId: "prod-1", quantity: 1, price: 45000, discount: 0 },
      { productId: "prod-5", quantity: 2, price: 8500, discount: 1000 },
    ],
    subtotal: 61000,
    tax: 10980,
    discount: 1000,
    total: 70980,
    status: "approved",
    versions: [],
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "quot-2",
    customerId: "cust-2",
    employeeId: "emp-1",
    items: [
      { productId: "prod-2", quantity: 1, price: 28000, discount: 0 },
      { productId: "prod-3", quantity: 4, price: 12000, discount: 2000 },
    ],
    subtotal: 76000,
    tax: 13680,
    discount: 2000,
    total: 87680,
    status: "sent",
    versions: [],
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

export const DUMMY_EMPLOYEES = [
  {
    id: "emp-1",
    name: "John Sales",
    email: "employee@furniture.com",
    phone: "+1234567891",
    role: "Sales Staff",
    status: "active",
    quotations: 12,
    conversionRate: 65,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=john",
  },
  {
    id: "emp-2",
    name: "Sarah Manager",
    email: "sarah@furniture.com",
    phone: "+1234567892",
    role: "Manager",
    status: "active",
    quotations: 28,
    conversionRate: 78,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sarah",
  },
  {
    id: "emp-3",
    name: "Mike Designer",
    email: "mike@furniture.com",
    phone: "+1234567893",
    role: "Designer",
    status: "active",
    quotations: 8,
    conversionRate: 72,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=mike",
  },
]
